version: "3.9"

services:
  postgresdb:
    image: postgres:14.10
    restart: always
    environment:
      DATABASE_HOST: ${SPRING_DATASOURCE_HOST}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdb:/var/lib/postgresql/data